# [실습-1] BMI 지수 계산 및 과체중 이상인 BMI 값 확인
- 10명에 대한 키와 몸무게가 들어있는 'height_weight.txt'를 읽어 각 사랆별 BMI 지수를 구하고 비만 전 단계 이상인 사람들의 BMI값 확인

<pre>
    BMI 지수 = 몸무게(kg) / 키(M)의 제곱
    체질량지수의 범위 값에 따른 비만도 값
    
    18.5 미만 -> 저체중
    18.5 ~ 22.9 -> 정상
    23 ~ 24.9 -> 비만 전 단계
    25 ~ 29 -> 비만 1단계
    30 ~ 34.9 -> 비만 2단계
    35 이상 -> 고도비만
</pre>

In [1]:
import numpy as np

data = np.loadtxt('height_weight.txt', delimiter=',') # 파일명, 구분자(어떤 문자로 구분할것인지)
print(data)

[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]


In [5]:
# 키와 몸무게 데이터 추출

height = data[0]  * 0.01
print(height)
weight = data[1]
print(weight)

[1.752 1.803 1.75  1.692 1.852 1.88  1.776 1.782 1.77  1.79 ]
[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]


In [10]:
# BMI 계산

bmi = np.divide(weight, height**2)
# bmi = weight / (height**2)
print(bmi)

[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]


In [15]:
# 과체중 (BMI 23이상)인 사람들의 BMI 확인
# print(bmi[bmi >= 23])

과체중 = bmi[bmi >= 23]
print(과체중)

print(bmi[np.logical_and(bmi>=23, bmi<25)])

[27.07018468 25.86122449 24.20652885 23.14392095 23.62028791 25.59220998]
[24.20652885 23.14392095 23.62028791]


# [실습-2] 국가건강검진 혈압혈당 데이터 분석
- loadtxt() 함수 이용해 데이터 읽기: `skiprows = 1 파라미터` 추가해서 첫 행 읽기를 건너뜀
- 데이터 구조
    - 성별: 1 남자, 2 여자
    - 연령그룹: 1(20-24), 2(25-26), ...25~74세까지 2살 간격 1개 그룹으로 지정 27그룹(74세 이상)
    - 고혈압 당뇨병 진료여부: 1 고혈압 및 당뇨 진료 내역 있음, 2 고혈압 진료 내역 있음, 3 당뇨 진료 내역 있음, 4 고혈압 당뇨 진료내역 없음
    - 정상혈압: 수축기 혈압 120mmHg 미만, 확장기 혈압 80mmHg 미만
    - 공복혈당 수치: 126mg/dL 이상 -> 당뇨, 100mg/dL 미만 -> 정상
    
- 분석내용
    - 데이터 로딩, 전체 레코드 수와 상위 5개 데이터 확인, 데이터 모양 확인
    - 각 컬럼의 유니크 값 확인: (컬럼에 대한 unique 값 확인: unique() 함수 이용)
    - 여성과 남성의 데이터 수 확인
    - 여성과 남성의 수축기 혈압과 이완기 혈압의 평균값 확인
    - 정상 혈압 남자 및 여자 수 확인
    - 당뇨 질환(공복혈당 수치 126이상)을 가지고 있는 사람들의 평균 체질량 지수 확인

In [3]:
# 데이터 로드 / 데이터 모양 및 수 확인
import numpy as np

data = np.loadtxt('국가건강검진_혈압혈당데이터.csv', delimiter=',', skiprows=1)

print(data.shape)
print('레코드 수: ', len(data))
print('상위 5개 데이터')
top5 = data[0:5, :] # 1행부터 5행까지 : 모든 열
print(top5)

(1000000, 7)
레코드 수:  1000000
상위 5개 데이터
[[  1.    1.  116.   78.   94.    4.   16.6]
 [  1.    1.  100.   60.   79.    4.   22.3]
 [  1.    1.  100.   60.   87.    4.   21.9]
 [  1.    1.  111.   70.   72.    4.   20.2]
 [  1.    1.  120.   80.   98.    4.   20. ]]


In [4]:
# 각 컬럼의 유니크 값 확인

print('성별 값: ', np.unique(data[:, 0]))
print('연령 값: ', np.unique(data[:, 1]))
print('고혈압 당뇨 진료여부 값: ', np.unique(data[:, 5]))

성별 값:  [1. 2.]
연령 값:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27.]
고혈압 당뇨 진료여부 값:  [1. 2. 3. 4.]


In [5]:
# 여성과 남성의 데이터 수 확인
print('남성 데이터 수: ', len(data[data[:,0] == 1]))
print('여성 데이터 수: ', len(data[data[:,0] == 2]))

남성 데이터 수:  510227
여성 데이터 수:  489773


In [6]:
# 여성과 남성의 수축기 혈압과 이완기 혈압의 평균값 확인
male_sbp_mean = np.mean(data[data[:,0]==1][:,2])
print("남성의 수축기 평균 혈압:%.2f"%male_sbp_mean)

male_dbp_mean = np.mean(data[data[:,0]==1][:,3])
print("남성의 이완기 평균 혈압:%.2f"%male_dbp_mean)

female_sbp_mean = np.mean(data[data[:,0]==2][:,2])
print("여성의 수축기 평균 혈압:%.2f"%female_sbp_mean)

female_dbp_mean = np.mean(data[data[:,0]==2][:,3])
print("여성의 이완기 평균 혈압:%.2f"%female_dbp_mean)

남성의 수축기 평균 혈압:124.28
남성의 이완기 평균 혈압:77.61
여성의 수축기 평균 혈압:119.36
여성의 이완기 평균 혈압:73.88


In [37]:
# 정상혈압 남자 및 여자 수 확인
nbp_masking = np.logical_and(data[:,2]<120, data[:,3] < 80)

nbp = data[nbp_masking]
print("정상혈압 남자 수:", len(nbp[nbp[:,0]==1]))
print("정상혈압 여자 수:", len(nbp[nbp[:,0]==2]))

정상혈압 남자 수: 158007
정상혈압 여자 수: 230707


In [41]:
# 당뇨 질환을 가지고 있는 사람들의 평균 BMI 값

disease = data[data[:,4]>=126]
print(disease[0:5,:])
#print(np.mean(disease[:,6]))
print(np.mean(disease[:, -1]))

[[  1.    1.  130.   80.  130.    4.   27.5]
 [  1.    1.  135.   85.  130.    4.   31.6]
 [  1.    1.  110.   60.  128.    4.   21.8]
 [  1.    1.  124.   62.  129.    4.   21.5]
 [  1.    1.  120.   80.  136.    4.   21.4]]
25.168695210981763
25.168695210981763


# [실습-3] 시애틀 강수량 데이터 분석
- 데이터 로딩
- 강수령(PRCP)이 많은 날 상위 10일 확인
- 1월 강수량만 출력
- 1월에 내린 강수량의 합, 평균 확인
- 1년동안 강수량이 40미만으로 내린 날이 몇일인지?

In [72]:
# 데이터 로딩
import numpy as np

data = np.loadtxt('Seattle2014.csv', delimiter=',', skiprows=1, dtype=object)
print(data[:5,:])

[['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140101' '0' '0' '0' '72' '33' '12' '340' '310' '36' '40' '-9999'
  '-9999' '-9999' '-9999']
 ['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140102' '41' '0' '0' '106' '61' '32' '190' '200' '94' '116' '-9999'
  '-9999' '-9999' '-9999']
 ['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140103' '15' '0' '0' '89' '28' '26' '30' '50' '63' '72' '1' '-9999'
  '-9999' '-9999']
 ['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140104' '0' '0' '0' '78' '6' '27' '40' '40' '45' '58' '1' '-9999'
  '-9999' '-9999']
 ['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140105' '0' '0' '0' '83' '-5' '37' '10' '10' '67' '76' '-9999'
  '-9999' '-9999' '-9999']]


In [77]:
# 강수량이 많은 날 상위 10일 확인

PRCP2 = data[:,2:4]
PRCP1 = np.array(PRCP2, dtype=int)
PRCP = np.sort(PRCP1, axis=0)[::-1]
print(PRCP[:10,:])

[[20141231      467]
 [20141230      343]
 [20141229      333]
 [20141228      323]
 [20141227      320]
 [20141226      277]
 [20141225      264]
 [20141224      254]
 [20141223      221]
 [20141222      216]]


In [142]:
# 쌤 버전
# 강수량이 많은 날 상위 10일 확인

prcp_data = data[:,3].astype(np.int32)
a = np.sort(prcp_data)[::-1]
print(a[:10])

[467 343 333 323 320 277 264 254 221 216]


In [3]:
# 1월 강수량만 출력

jan = data[0:31, 2:4]
jan_np = np.array(jan, dtype=int)
print(jan_np)

[[20140101        0]
 [20140102       41]
 [20140103       15]
 [20140104        0]
 [20140105        0]
 [20140106        3]
 [20140107      122]
 [20140108       97]
 [20140109       58]
 [20140110       43]
 [20140111      213]
 [20140112       15]
 [20140113        0]
 [20140114        0]
 [20140115        0]
 [20140116        0]
 [20140117        0]
 [20140118        0]
 [20140119        0]
 [20140120        0]
 [20140121        0]
 [20140122        5]
 [20140123        0]
 [20140124        0]
 [20140125        0]
 [20140126        0]
 [20140127        0]
 [20140128       89]
 [20140129      216]
 [20140130        0]
 [20140131       23]]


In [180]:
# 쌤 버전
# 1월 강수량만 확인

prcp_data = data[:,[2,3]]

month_prcp_data = np.array([ [date[4:6], prcp] for date, prcp in prcp_data], dtype= np.int32)
# print(month_prcp_data)

jan_prcp = month_prcp_data[month_prcp_data[:,0] == 1]
jan_prcp = jan_prcp[:,1]
print(len(jan_prcp))
print(jan_prcp)

31
[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]


In [7]:
# 1월에 내린 강수량의 합, 평균

print(np.sum(jan_np[:,1], axis=0))
#print(np.average(jan_np, axis=0))
print(np.mean(jan_np[:,1], axis=0))

940
30.322580645161292


In [182]:
# 쌤 버전
# 1월에 내린 강수량의 합, 평균

total_jan_prcp = np.sum(jan_prcp)
print("1월에 내린 강수량 합: %d"%total_jan_prcp)
avg_jan_prcp = np.mean(jan_prcp)
print("1월에 내린 강수량 평균: %.2f"%avg_jan_prcp)

1월에 내린 강수량 합: 940
1월에 내린 강수량 평균: 30.32


In [176]:
# 1년동안 강수량이 40미만으로 내린 날

data_np = np.array(data[:,2:4], dtype=int)
# print(data_np)
print(len(data_np[data_np[:,-1] < 40]))
print(data_np[data_np[:,-1] < 40])

277
[[20140101        0]
 [20140103       15]
 [20140104        0]
 [20140105        0]
 [20140106        3]
 [20140112       15]
 [20140113        0]
 [20140114        0]
 [20140115        0]
 [20140116        0]
 [20140117        0]
 [20140118        0]
 [20140119        0]
 [20140120        0]
 [20140121        0]
 [20140122        5]
 [20140123        0]
 [20140124        0]
 [20140125        0]
 [20140126        0]
 [20140127        0]
 [20140130        0]
 [20140131       23]
 [20140201       20]
 [20140202        0]
 [20140203        0]
 [20140204        0]
 [20140205        0]
 [20140206        0]
 [20140207        0]
 [20140209        5]
 [20140213       18]
 [20140219       10]
 [20140220       30]
 [20140221       28]
 [20140222       25]
 [20140225        3]
 [20140226        0]
 [20140227        0]
 [20140228        0]
 [20140301        5]
 [20140306       30]
 [20140307        0]
 [20140311        0]
 [20140312        0]
 [20140313        5]
 [20140317        3]
 [2014031

In [8]:
# 쌤 버전
# 1년동안 강수량이 40미만으로 내린 날

prcp_data = data[:,3:4].astype(int)
under_40 = prcp_data[prcp_data[:] < 40]
print(len(under_40))
print(under_40)

277
[ 0 15  0  0  3 15  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0  0 23 20
  0  0  0  0  0  0  5 18 10 30 28 25  3  0  0  0  5 30  0  0  0  5  3  0
  5  0  0  0  0  0 36  3  0  0  0  0 25  0  0  0  0  0  0  0  0  0  5  0
  0  0 33  0  0  0  0  0  0  0 20  5  0  0  0  0  0  0  0  0  0  0  0  0
 38  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 18  0  5 36 13
  0  8  3  0  0  0  0  0  0 18 23  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  5  0  0  0
  0  0  0  0  0  5  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0 13  0
 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  3  0  0  0  3  0  0  8
  0  0  0  0  0  0  0  0  0  0  3  0  0 33  0 10 15  8  5  0 18  0  0  0
  0  0  0  0  0  0  0  0  0 36  5 13  3 33 36  0  0  0  0  8 30  0  0  0
  0  0  0 28 30  0  0  0  0 33  0  0  0]


# [실습-4] 영화 평점 분석
- 데이터 로딩 (데이터 형식: user_id::item_id::rating::timestamp)
- 상위 10개 데이터 출력하기
- 데이터 정보 확인 (크기, 차원..)
- 전체 데이터 평균 평점 구하기
- 사용자 아이디 1인 데이터 출력
- 사용자 아이기 1인 사람의 평균 평점
- 각 사용자별 평균 평점(unique)
- 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원 수 구하기

In [78]:
# 데이터 로딩 및 상위 10개 데이터 출력, 데이터 정보 확인
import numpy as np

movie = np.loadtxt('ratings.dat', delimiter='::', dtype=int)
print(movie[:10,:])

print(movie.ndim)
print(movie.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]]
2
(1000209, 4)


In [83]:
# 전체 데이터 평균 평점 구하기

avg_rating = np.mean(movie[:,[2]])
print("평균평점: %.2f"%avg_rating)

평균평점: 3.58


In [85]:
# 쌤 버전
# 전체 데이터 평균 평점 구하기

avg_ratings = np.mean(movie[:,2])
print("전체 사용자 평균평점: %.2f"%avg_ratings)

전체 사용자 평균평점: 3.58


In [86]:
# 사용자 아이디 1인 사람의 데이터 출력

user_1 = movie[movie[:, 0] == 1]

print(len(user_1))
print(user_1)

53
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1      1270         5 978300055]
 [      

In [88]:
# 사용자 아이디가 1인 사람의 평균 평점

user_1_rating = np.mean(user_1[:,2])
print("아이디가 1인 사람의 평균 평점: %.2f"%user_1_rating)

아이디가 1인 사람의 평균 평점: 4.19


In [82]:
# 각 사용자별 평균 평점 구하기

unique_user = np.unique(movie[:,:])
print(unique_user)
print(len(unique_user))

avg_uni_user = np.mean(unique_user[:,[2]])
print(avg_uni_user)

[         1          2          3 ... 1046454443 1046454548 1046454590]
464495


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [92]:
# 각 사용자별 평균 평점

user_ids = np.unique(movie[:,0])
print(len(user_ids))

user_avg_rating = [[id, np.mean(movie[movie[:,0] == id][:,2])] for id in user_ids]
user_avg_rating = np.array(user_avg_rating, dtype=int)
print(user_avg_rating)

6040
[[   1    4]
 [   2    3]
 [   3    3]
 ...
 [6038    3]
 [6039    3]
 [6040    3]]


In [98]:
print("평균 총점이 4점 이상인 유저의 수")
print(len(user_avg_rating[user_avg_rating[:,1] >= 4]), '명')

평균 총점이 4점 이상인 유저의 수
1544 명
