### [문제-1] 길이가 10인 0-벡터를 만드세요.

In [2]:
import numpy as np

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


### [문제-2] 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [3]:
a = np.zeros(10, dtype=int)
print(a)

print(np.where(a[4], 1, a))

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [4]:
a = np.zeros(10)
a[5] = 1

print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


### [문제-3] 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [8]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### [문제-4] 위 벡터의 순서를 바꾸세요.

In [12]:
a = np.arange(49, 9, -1)
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### [문제-5] 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [14]:
a = np.arange(9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### [문제-6] 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [18]:
a = np.array([1, 2, 0, 0, 4, 0])

print(a[a!=0])

[1 2 4]


In [5]:
a = np.array([1, 2, 0, 0, 4, 0])
b = a[a !=0 ]
print(b)

[1 2 4]


### [문제-7] 3x3 단위 행렬(identity matrix)을 만드세요

In [19]:
print(np.identity(3, dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### [문제-8] 난수 원소를 가지는 3x3 행렬을 만드세요

In [8]:
a = np.random.rand(3,3)
print(a)

[[0.11667592 0.74961106 0.61026989]
 [0.30821102 0.91073627 0.68784653]
 [0.35241291 0.35429837 0.04203089]]


In [7]:
b = np.random.random((3,3))
print(b)

[[0.40096048 0.70767304 0.98762637]
 [0.47057888 0.02476553 0.96441243]
 [0.00540823 0.44362608 0.79745213]]


### [문제-9] 위에서 만든 난수 행렬에서 최대값/최솟값 원소를 찾으세요.

In [9]:
print(np.max(a))
print(np.min(a))

0.910736266008364
0.04203089148840067


In [12]:
a = np.random.rand((3,3))
max_value = np.amax(a)
min_value = np.amin(a)

print(max_value)
print(min_value)

TypeError: 'tuple' object cannot be interpreted as an integer

### [문제-10] 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [28]:
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

[-1.41334868  0.95395036  0.97916003]
[-0.20384153  0.57039863  0.1532046 ]


In [13]:
row_avg = np.average(a, axis=1)
print(row_avg)

col_avg = np.average(a, axis=0)
print(col_avg)

[0.49218562 0.63559794 0.24958073]
[0.25909995 0.67154857 0.44671577]


### [문제-11] 5x5짜리 정방행렬의 단위행렬을 생성하시오

In [29]:
print(np.identity(5, dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [14]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### [문제-12] 10~50까지 값 9개를 정수로 발생시켜 출력

In [19]:
a = np.random.randint(10, 51, size=9)
print(a)

[25 48 46 33 17 29 32 40 28]


### [문제-13] shape을 3x3변환

In [20]:
print(a.reshape((3,3)))

[[25 48 46]
 [33 17 29]
 [32 40 28]]


### [문제-14] 각 행끼리의 합을 구하여 출력

In [21]:
a = a.reshape((3,3))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[ 90 105 103]
[119  79 100]


In [22]:
row_sum = np.sum(a, axis=1)
print(row_sum)

[119  79 100]


### [문제-15] 각 열 중 최대값 구하여 출력

In [42]:
print(np.max(a, axis=0))

[28 27 40]


In [23]:
col_max = np.amax(a, axis=0)
print(col_max)

[33 48 46]


### [문제-16] 전체 요소의 평균을 구하여 출력

In [24]:
print(np.mean(a))

33.111111111111114


In [25]:
average = np.average(a)
print(average)

# mean = 산술평균
# average = 가중평균

33.111111111111114


### [문제-17] 1~10 사이의 정수를 요소로 하는 2x3 배열 생성

In [48]:
a = np.random.randint(10, size=6).reshape(2,3)
print(a)

[[5 7 2]
 [1 3 6]]


In [26]:
a = np.random.randint(1, 11, (2,3))
print(a)

[[1 3 6]
 [4 1 3]]


### [문제-18] 10~20 사이의 정수를 요소로 하는 3x2 배열 생성

In [28]:
b = np.random.randint(10, 21, size=6).reshape(3,2)
print(b)

[[16 18]
 [10 20]
 [17 16]]


In [27]:
b = np.random.randint(10, 21, (3,2))
print(b)

[[18 18]
 [10 20]
 [18 10]]


### [문제-19] 두 배열의 행렬 곱을 구하여 출력

In [31]:
print(a@b)

print(np.dot(a,b))
print(np.matmul(a,b))

# dot = 행렬과 스칼라의 곱 허용
# matmul = 행렬과 상수의 곱 허용 x

[[148 174]
 [125 140]]
[[148 174]
 [125 140]]
[[148 174]
 [125 140]]


### [문제-20] 1번째 배열의 전치 행렬을 구하여 출력

In [56]:
a = np.random.randint(10, size=6).reshape(2,3)

x = a.T
print(x)

[[0 9]
 [3 7]
 [2 8]]


### [문제-21] 로또 번호 생성하기 (1~46 사이의 중복되지 않은 정수 6개 추출)

In [53]:
a = np.random.randint(47, size=47)
lotto = np.random.choice(a, size=(6,), replace=False)

print(a)
print(lotto)

[46 11 40 27 13 42  6  8 39 19 43 39 38 45  2 45 17 23 28 45 39 31 26 16
 39 37 29  7 34 41  5 17 31 35  7  3 11  9 10 28  4 21 45 30 15 23 33]
[13  7 39 11 45 26]


In [39]:
lotto = np.random.choice(np.arange(1,47), 6, replace=False)
print(lotto)

[42 11 41 33 16 39]
